#!/bin/bash

#%include bashout.sh colours.sh askuser.sh

check_ppa_exists() {
	grep minetest /etc/apt/sources.list* -r -q
}

add_ppa() {
	check_ppa_exists && {
		warne "PPA already setup - you may already have installed Minetest Server Tools."
		uconfirm "Proceed with installation ?" || faile "Aborted."
		return
	}
	add-apt-repository -y ppa:minetestdevs/stable
}

install_binaries() {
	apt update
	apt install minetest libleveldb1v5
}

add_python_tools() {
	apt install python3-pip -y
	pip3 install --upgrade pip3
	pip3 install jinja2
}

add_supporting_files() {
	#FIXME -u option makes sure we don't wallop anything newer than our copy
	#    we would really want to never overwrite anything, just in case...
	rsync -au pkg/ /
}

main() {
	[[ "$UID" = 0 ]] || faile "You must be root to run this script."

	add_ppa || faile "Could not install minetest PPA"
	install_binaries || faile "Could not install minetest"
	add_python_tools || faile "COuld not add essential python tools"

	add_supporting_files
	
	infoe "Done."
}
